rtp.app.url=https://banka-bankos-qa2.finzly.io/rtp
#rtp.app.url=http://localhost:8088/rtp
api.client.id=finzly.payment.apiaccount
api.secret=4b363f19-cd78-4c94-9f3c-6094647568d3
api.auth.url=https://security-qa2.finzly.io/auth/realms/BANKOS-QA2-BANKA-BANK/protocol/openid-connect/token
