package com.finzly.galaxy.rtp.validator.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Pattern;

/**
 * Service to validate values against RTP Message Specification requirements
 * before they are written to XML tags.
 * 
 * This ensures all generated values comply with the RTP specification format,
 * length, and content requirements as defined in the RTP Message Specification v5.0.
 */
@Service
@Slf4j
public class RtpValueValidationService {

    // Regex patterns from RTP specification
    private static final Pattern MSG_ID_PATTERN = Pattern.compile(
        "^M[0-9]{4}(((01|03|05|07|08|10|12)((0[1-9])|([1-2][0-9])|(3[0-1])))|((04|06|09|11)((0[1-9])|([1-2][0-9])|30))|((02)((0[1-9])|([1-2][0-9]))))[A-Z0-9]{11}.*"
    );
    
    private static final Pattern INSTR_ID_PATTERN = Pattern.compile(
        "^[0-9]{4}(((01|03|05|07|08|10|12)((0[1-9])|([1-2][0-9])|(3[0-1])))|((04|06|09|11)((0[1-9])|([1-2][0-9])|30))|((02)((0[1-9])|([1-2][0-9]))))[A-Z0-9]{11}.*"
    );

    /**
     * Validate and fix MsgId value according to RTP specification (Index 1.1)
     * Format: MYYYYMMDDbbbbbbbbbbbbBAAAnnnnnnnnnnn (35 chars)
     * - Pos. 01-01: Prefix 'M'
     * - Pos. 02-09: File creation date in format YYYYMMDD
     * - Pos. 10-20: Participant ID (11 characters)
     * - Pos. 21-21: Message generation source ("B" if generated by a Participant)
     * - Pos. 22-24: Discretionary bank field (3 digit alpha numeric)
     * - Pos. 25-35: Message serial number (11 numeric characters)
     * 
     * @param msgId The MsgId value to validate
     * @param participantId Participant ID (11 chars, default: "101010101MT")
     * @param bankField Discretionary bank field (3 chars, default: "OTS")
     * @return Validated and corrected MsgId, or null if cannot be fixed
     */
    public String validateAndFixMsgId(String msgId, String participantId, String bankField) {
        if (msgId == null || msgId.trim().isEmpty()) {
            log.warn("MsgId is null or empty, generating new one");
            return generateValidMsgId(participantId, bankField);
        }
        
        // Check length
        if (msgId.length() != 35) {
            log.warn("MsgId length is {} (expected 35), fixing: {}", msgId.length(), msgId);
            return generateValidMsgId(participantId, bankField);
        }
        
        // Check starts with 'M'
        if (!msgId.startsWith("M")) {
            log.warn("MsgId does not start with 'M', fixing: {}", msgId);
            return generateValidMsgId(participantId, bankField);
        }
        
        // Check date format (positions 2-9)
        String dateStr = msgId.substring(1, 9);
        if (!isValidDate(dateStr)) {
            log.warn("MsgId date format invalid (positions 2-9: {}), fixing: {}", dateStr, msgId);
            return generateValidMsgId(participantId, bankField);
        }
        
        // Validate pattern
        if (!MSG_ID_PATTERN.matcher(msgId).matches()) {
            log.warn("MsgId does not match RTP specification pattern, fixing: {}", msgId);
            return generateValidMsgId(participantId, bankField);
        }
        
        return msgId;
    }

    /**
     * Generate a valid MsgId according to RTP specification
     */
    private String generateValidMsgId(String participantId, String bankField) {
        if (participantId == null || participantId.length() != 11) {
            participantId = "101010101MT"; // Default participant ID
        }
        if (bankField == null || bankField.length() != 3) {
            bankField = "OTS"; // Default bank field
        }
        
        String dateStr = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"));
        String source = "B"; // Participant generated
        String serialNumber = String.format("%011d", System.currentTimeMillis() % 100000000000L);
        
        return "M" + dateStr + participantId + source + bankField + serialNumber;
    }

    /**
     * Validate and fix InstrId value according to RTP specification (Index 2.2)
     * Format: YYYYMMDDbbbbbbbbbbbbBAAAAnnnnnnnnnnn (35 chars)
     * - Pos. 01-08: File creation date in format YYYYMMDD
     * - Pos. 09-19: Participant ID (11 characters)
     * - Pos. 20-20: Message generation source ("B" if generated by a Participant)
     * - Pos. 21-24: Discretionary bank field (4 digit alpha numeric)
     * - Pos. 25-35: Message serial number (11 numeric characters)
     * 
     * @param instrId The InstrId value to validate
     * @param participantId Participant ID (11 chars, default: "101010101MT")
     * @param bankField Discretionary bank field (4 chars, default: "AKSG")
     * @return Validated and corrected InstrId, or null if cannot be fixed
     */
    public String validateAndFixInstrId(String instrId, String participantId, String bankField) {
        if (instrId == null || instrId.trim().isEmpty()) {
            log.warn("InstrId is null or empty, generating new one");
            return generateValidInstrId(participantId, bankField);
        }
        
        // Check length
        if (instrId.length() != 35) {
            log.warn("InstrId length is {} (expected 35), fixing: {}", instrId.length(), instrId);
            return generateValidInstrId(participantId, bankField);
        }
        
        // Check date format (positions 1-8)
        String dateStr = instrId.substring(0, 8);
        if (!isValidDate(dateStr)) {
            log.warn("InstrId date format invalid (positions 1-8: {}), fixing: {}", dateStr, instrId);
            return generateValidInstrId(participantId, bankField);
        }
        
        // Validate pattern
        if (!INSTR_ID_PATTERN.matcher(instrId).matches()) {
            log.warn("InstrId does not match RTP specification pattern, fixing: {}", instrId);
            return generateValidInstrId(participantId, bankField);
        }
        
        return instrId;
    }

    /**
     * Generate a valid InstrId according to RTP specification
     */
    private String generateValidInstrId(String participantId, String bankField) {
        if (participantId == null || participantId.length() != 11) {
            participantId = "101010101MT"; // Default participant ID
        }
        if (bankField == null || bankField.length() != 4) {
            bankField = "AKSG"; // Default bank field
        }
        
        String dateStr = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"));
        String source = "B"; // Participant generated
        String serialNumber = String.format("%011d", System.currentTimeMillis() % 100000000000L);
        
        return dateStr + participantId + source + bankField + serialNumber;
    }

    /**
     * Validate and fix TxId value according to RTP specification (Index 2.4)
     * Format: YYYYMMDDbbbbbbbbbbbbBAAAAnnnnnnnnnnn (35 chars)
     * Same format as InstrId
     * 
     * @param txId The TxId value to validate
     * @param participantId Participant ID (11 chars, default: "101010101MT")
     * @param bankField Discretionary bank field (4 chars, default: "AKSG")
     * @return Validated and corrected TxId, or null if cannot be fixed
     */
    public String validateAndFixTxId(String txId, String participantId, String bankField) {
        // TxId uses same format as InstrId
        return validateAndFixInstrId(txId, participantId, bankField);
    }

    /**
     * Validate and fix Service Level Code according to RTP specification (Index 2.11)
     * Must be 'SDVA' (Same Day Value)
     * 
     * @param svcLvlCd The Service Level Code to validate
     * @return Always returns 'SDVA' per RTP specification
     */
    public String validateAndFixSvcLvlCd(String svcLvlCd) {
        if (svcLvlCd == null || !svcLvlCd.equals("SDVA")) {
            log.warn("Service Level Code is '{}' (expected 'SDVA'), fixing to 'SDVA'", svcLvlCd);
            return "SDVA";
        }
        return svcLvlCd;
    }

    /**
     * Validate and fix Name fields according to RTP specification
     * - Max 140 characters for party names (Index 2.855, 2.1102)
     * - Max 70 characters for account names (Index 2.929, 2.1176)
     * - Must not contain test data patterns
     * 
     * @param name The name value to validate
     * @param maxLength Maximum allowed length
     * @return Validated name, or null if invalid
     */
    public String validateAndFixName(String name, int maxLength) {
        if (name == null || name.trim().isEmpty()) {
            return null;
        }
        
        name = name.trim();
        
        // Check for test data patterns
        String lowerName = name.toLowerCase();
        if (lowerName.contains("test") || 
            lowerName.contains("sample") || 
            lowerName.contains("participant valid") ||
            lowerName.contains("default") ||
            lowerName.equals("john smith") ||
            lowerName.equals("jane doe")) {
            log.warn("Name contains test data pattern: '{}', needs production value", name);
            return null; // Return null to trigger fallback
        }
        
        // Check length
        if (name.length() > maxLength) {
            log.warn("Name length {} exceeds maximum {}: '{}'", name.length(), maxLength, name);
            return name.substring(0, maxLength);
        }
        
        return name;
    }

    /**
     * Validate and fix Currency Code according to RTP specification
     * Must be 'USD' (US Dollar)
     * 
     * @param ccy The currency code to validate
     * @return Always returns 'USD' per RTP specification
     */
    public String validateAndFixCurrency(String ccy) {
        if (ccy == null || !ccy.equals("USD")) {
            log.warn("Currency code is '{}' (expected 'USD'), fixing to 'USD'", ccy);
            return "USD";
        }
        return ccy;
    }

    /**
     * Validate and fix Settlement Method according to RTP specification (Index 1.10)
     * Must be 'CLRG' (Clearing System)
     * 
     * @param sttlmMtd The settlement method to validate
     * @return Always returns 'CLRG' per RTP specification
     */
    public String validateAndFixSettlementMethod(String sttlmMtd) {
        if (sttlmMtd == null || !sttlmMtd.equals("CLRG")) {
            log.warn("Settlement Method is '{}' (expected 'CLRG'), fixing to 'CLRG'", sttlmMtd);
            return "CLRG";
        }
        return sttlmMtd;
    }

    /**
     * Validate and fix Clearing System Code according to RTP specification (Index 1.31)
     * Must be 'TCH' (The Clearing House)
     * 
     * @param clrSysCd The clearing system code to validate
     * @return Always returns 'TCH' per RTP specification
     */
    public String validateAndFixClearingSystemCode(String clrSysCd) {
        if (clrSysCd == null || !clrSysCd.equals("TCH")) {
            log.warn("Clearing System Code is '{}' (expected 'TCH'), fixing to 'TCH'", clrSysCd);
            return "TCH";
        }
        return clrSysCd;
    }

    /**
     * Validate and fix Charge Bearer according to RTP specification (Index 2.36)
     * Must be 'SLEV' (Following Service Level)
     * 
     * @param chrgBr The charge bearer to validate
     * @return Always returns 'SLEV' per RTP specification
     */
    public String validateAndFixChargeBearer(String chrgBr) {
        if (chrgBr == null || !chrgBr.equals("SLEV")) {
            log.warn("Charge Bearer is '{}' (expected 'SLEV'), fixing to 'SLEV'", chrgBr);
            return "SLEV";
        }
        return chrgBr;
    }

    /**
     * Validate and fix Number of Transactions according to RTP specification (Index 1.4)
     * Must be '1' (only one Credit Transfer per pacs.008 message)
     * 
     * @param nbOfTxs The number of transactions to validate
     * @return Always returns '1' per RTP specification
     */
    public String validateAndFixNbOfTxs(String nbOfTxs) {
        if (nbOfTxs == null || !nbOfTxs.equals("1")) {
            log.warn("Number of Transactions is '{}' (expected '1'), fixing to '1'", nbOfTxs);
            return "1";
        }
        return nbOfTxs;
    }

    /**
     * Validate date format YYYYMMDD
     */
    private boolean isValidDate(String dateStr) {
        if (dateStr == null || dateStr.length() != 8) {
            return false;
        }
        try {
            LocalDate.parse(dateStr, DateTimeFormatter.ofPattern("yyyyMMdd"));
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Validate a value for a specific tag according to RTP specification
     * This is the main validation method called before writing values to XML
     * 
     * @param tagName The XML tag name (uppercase)
     * @param value The value to validate
     * @param index The tag index from RTP specification
     * @return Validated and corrected value, or original value if valid
     */
    public String validateValue(String tagName, String value, String index) {
        if (value == null) {
            return null;
        }

        // Validate based on tag name and index
        switch (tagName) {
            case "MSGID":
                return validateAndFixMsgId(value, "101010101MT", "OTS");
            
            case "INSTRID":
                return validateAndFixInstrId(value, "101010101MT", "AKSG");
            
            case "TXID":
                return validateAndFixTxId(value, "101010101MT", "AKSG");
            
            case "CD":
                if (index != null && index.startsWith("2.11")) {
                    // Service Level Code
                    return validateAndFixSvcLvlCd(value);
                } else if (index != null && index.startsWith("1.31")) {
                    // Clearing System Code
                    return validateAndFixClearingSystemCode(value);
                }
                return value;
            
            case "CCY":
                return validateAndFixCurrency(value);
            
            case "STTLMTD":
                return validateAndFixSettlementMethod(value);
            
            case "CHRGBR":
                return validateAndFixChargeBearer(value);
            
            case "NBOFTXS":
                return validateAndFixNbOfTxs(value);
            
            case "NM":
                if (index != null && (index.startsWith("2.855") || index.startsWith("2.1102"))) {
                    // Party names (max 140 chars)
                    return validateAndFixName(value, 140);
                } else if (index != null && (index.startsWith("2.929") || index.startsWith("2.1176"))) {
                    // Account names (max 70 chars)
                    return validateAndFixName(value, 70);
                }
                return value;
            
            default:
                return value;
        }
    }
}

